export const categories=[
    'Amazon',
    'Google',
    'Microsoft',
    'Facebook',
    'Apple',
    'Adobe',
    'Uber',
    'Goldman Sachs',
    'Oracle',
    'Paytm',
    'LinkedIn',
    'Saleforce',
    'Twitter',
    'VMware',
    'Infosys',
    'Wipro',
    'Bloomberg',
    'Snapchat',
    'TCS'
];